apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: vegeta
  labels:
    app: vegeta
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vegeta 
  template:
    metadata:
      labels:
        app: vegeta
    spec:
      containers:
      - name: vegeta
        image: peihsinsu/vegeta
        env:
        - name: URL
          value: "http://35.185.139.252/index.html"
        - name: DURATION
          value: "30s"
        - name: RATE
          value: "200"
